# -*- coding: utf-8 -*-
"""Say_Hello_World!_With_Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EkblQDMrUmwBimmZVuVdHG-d5swZH5Kx

Check Tutorial tab to know how to to solve.

Here is a sample line of code that can be executed in Python:

```print("Hello, World!")```

You can just as easily store a string as a variable and then print it to stdout:

```
my_string = "Hello, World!"
print(my_string)
```
The above code will print Hello, World! on your screen. Try it yourself in the editor below!

Input Format

You do not need to read any input in this challenge.

Output Format

Print Hello, World! to stdout.

Sample Output 0

Hello, World!
"""

print("Hello, World!")